import { describe, expect, it } from "vitest";
// @ts-expect-error This viewer dependency does not ship TypeScript declarations.
import { PlyParser } from "@mkkellogg/gaussian-splats-3d";
import fixture from "./fixtures/text-target.json";

interface ParsedSplats {
  splatCount: number;
  splats: number[][];
}

describe("text-to-splat PLY compatibility", () => {
  it("loads the Python export in the frontend viewer's real PLY parser", () => {
    // This fixture is generated by the notebook's Python writer. No mocked decoder,
    // GPU, WebGL or downloaded model is involved. Spark's WASM renderer is separate.
    const bytes = Uint8Array.from(atob(fixture.base64), value => value.charCodeAt(0));
    const parsed = PlyParser.parseToUncompressedSplatArray(bytes.buffer) as ParsedSplats;
    expect(parsed.splatCount).toBe(fixture.count);
    expect(parsed.splats).toHaveLength(fixture.count);
    for (let index = 0; index < fixture.count; index++) {
      const row = parsed.splats[index];
      expect(row.every(Number.isFinite)).toBe(true);
      // Viewer array: xyz, decoded linear scale, normalized wxyz, RGB8, alpha8.
      fixture.means[index].forEach((value, axis) => expect(row[axis]).toBeCloseTo(value, 5));
      fixture.scales[index].forEach((value, axis) => expect(row[3 + axis]).toBeCloseTo(value, 5));
      fixture.quats[index].forEach((value, axis) => expect(row[6 + axis]).toBeCloseTo(value, 5));
      fixture.rgb[index].forEach((value, channel) => {
        expect(Math.abs(row[10 + channel] / 255 - value)).toBeLessThanOrEqual(1.01 / 255);
      });
      expect(Math.abs(row[13] / 255 - fixture.opacity[index])).toBeLessThanOrEqual(1.01 / 255);
    }
  });
});
